# Generated by Django 5.2.12 on 2026-03-21 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100)),
                ('semester', models.PositiveIntegerField(blank=True, null=True)),
                ('subject_needed', models.CharField(blank=True, max_length=100)),
                ('preferred_mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('both', 'Both')], default='online', max_length=20)),
                ('availability', models.CharField(blank=True, max_length=200)),
                ('q1', models.CharField(blank=True, max_length=50)),
                ('q2', models.CharField(blank=True, max_length=50)),
                ('q3', models.CharField(blank=True, max_length=50)),
                ('learning_style', models.CharField(blank=True, choices=[('visual', 'Visual'), ('practical', 'Practical'), ('conceptual', 'Conceptual'), ('discussion', 'Discussion')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100)),
                ('subjects', models.CharField(blank=True, help_text='Comma separated subjects', max_length=200)),
                ('teaching_style', models.CharField(blank=True, choices=[('visual', 'Diagram Based'), ('practical', 'Problem Solving'), ('conceptual', 'Concept Explanation'), ('discussion', 'Interactive Discussion')], max_length=20)),
                ('available_mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('both', 'Both')], default='online', max_length=20)),
                ('availability', models.CharField(blank=True, max_length=200)),
                ('max_students', models.PositiveIntegerField(default=1)),
                ('tutor_score', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
