# Generated by Django 5.2.12 on 2026-03-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='subjects',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
